name: 'PR Labeler'
description: 'Automatically labels your PRs based on their content'
author: 'Eugene Kravtsov'
inputs:
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/pr-labeler.yml'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: "composite"
  steps:
    - name: Query the PR info
      run: |
        URL_CONF="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.pull_request.base.ref }}/${{ inputs.configuration-path }}"
        CONF=$(curl -s -X GET -G $URL_CONF \
          --header 'Authorization: token ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json')
        LABELS=$( echo $CONF | jq '.[] .label')
        echo Labels $LABELS
        
        URL_FILES="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL_FILES \
          --header 'Authorization: token ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' | jq '.[] .filename')
        echo $FILES
        
        INDEX=0
        for LBL in $LABELS
        do
          echo $LBL
          echo $INDEX
          echo $CONF | jq --argjson INDEX $INDEX --arg FILES "$FILES" '.[$INDEX] .path | .[] | inside($FILES)'
          let INDEX++
        done
        
      shell: bash