name: 'PR Labeler'
description: 'Automatically labels your PRs based on their content'
author: 'Eugene Kravtsov'
inputs:
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/pr-labeler.json'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: "composite"
  steps:
    - name: Query the PR info
      run: |
        URL_CONF="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.pull_request.base.ref }}/${{ inputs.configuration-path }}"
        CONF=$(curl -s -X GET -G $URL_CONF \
          --header 'Authorization: token ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json')
        LABELS=$( echo $CONF | jq '.[] .label')
        echo "Labels:" $LABELS
        
        URL_LABELS="https://api.github.com/repos/${{ github.repository }}/labels"
        
        URL_FILES="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL_FILES \
          --header 'Authorization: token ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' | jq '.[] .filename')
        echo "Files:" $FILES
        
        INDEX=0
        for LBL in $LABELS
        do
          if [ $(echo $CONF | jq --arg INDEX $INDEX --arg FILES "$FILES" '.[$INDEX|tonumber] .path | any(.[]; inside($FILES))') = "true" ]
          then
            echo $LBL
            
            echo $(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" -X GET -G "$URL_LABELS/$LBL")
            
            COLOR=$(echo $CONF | jq --arg INDEX $INDEX '.[$INDEX|tonumber] .color')
            curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" -X POST $URL_LABELS \
              -d "{\"name\": $LBL, \"color\": $COLOR}"
            
            curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" -X POST \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" -d "[ $LBL ]"
          else
            echo Not $LBL
          fi
          INDEX=$((INDEX+1))
        done
        
      shell: bash